{"name": "insights.specs.Specs.satellite_custom_ca_chain", "exec_time": 5.269050598144531e-05, "errors": ["Traceback (most recent call last):\n  File \"/var/lib/insights/last_stable.egg/insights/core/serde.py\", line 195, in dehydrate\n    doc[\"results\"] = marshal(value, root=self.data, pool=self.pool)\n  File \"/var/lib/insights/last_stable.egg/insights/core/serde.py\", line 106, in marshal\n    return f(v)\n  File \"/var/lib/insights/last_stable.egg/insights/core/serde.py\", line 85, in serialize\n    \"object\": to_dict(obj, root=root),\n  File \"/var/lib/insights/last_stable.egg/insights/core/spec_factory.py\", line 1017, in serialize_command_output\n    rc = obj.write(dst)\n  File \"/var/lib/insights/last_stable.egg/insights/core/spec_factory.py\", line 396, in write\n    return p.write(dst, keep_rc=self.keep_rc)\n  File \"/var/lib/insights/last_stable.egg/insights/util/subproc.py\", line 155, in write\n    six.reraise(be.__class__, be, sys.exc_info()[2])\n  File \"/usr/lib/python3.6/site-packages/six.py\", line 693, in reraise\n    raise value\n  File \"/var/lib/insights/last_stable.egg/insights/util/subproc.py\", line 151, in write\n    raise CalledProcessError(rc, self.cmds[0], \"\")\ninsights.util.subproc.CalledProcessError: (2, ['timeout', '-s', '9', '120', '/usr/bin/awk', 'BEGIN { pipe=\"openssl x509 -noout -subject -enddate\"} /^-+BEGIN CERT/,/^-+END CERT/ { print | pipe } /^-+END CERT/ { close(pipe); printf(\"\\\\n\")}', '/etc/pki/katello/certs/katello-server-ca.crt'], '')\n"], "results": null, "ser_time": 0.005750179290771484}